const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const vm=require('node:vm');const {Readable,Writable}=require('node:stream');
const root=__dirname;let handler,captured;
const users={student:{uid:'student',name:'학생',role:'student',schoolId:'school-a',grade:1,classId:2,studentNumber:10201},teacher:{uid:'teacher',name:'교사',role:'teacher',schoolId:'school-a',grade:1,classId:2}};
const auth={isConfigured:()=>true,serverConfigured:()=>true,publicConfig:()=>({apiKey:'public',authDomain:'example',projectId:'p',appId:'a'}),authenticate:async req=>users[req.headers.cookie],safeProfile:x=>x,sameClass:(u,s,g,c)=>u.schoolId===s&&u.grade===g&&u.classId===c,cookie:()=>'',createSession:async()=>{throw Error('unused')}};
const storage={getUser:id=>id==='student'?users.student:null,getClassSettings:(...args)=>(captured=args,{schoolId:args[0],grade:args[1],classId:args[2]}),getStudentPracticeSessions:()=>[],getStudentBadges:()=>[],getDebateRoom:()=>({roomId:'r',endsAt:new Date(Date.now()+1000).toISOString(),messages:[]}),getTeacherObservations:()=>[{private:true}]};
const forbidden=new Proxy({}, {get(){throw Error('Unexpected private service access')}});const knowledge={cards:[{}],getEvidenceCards:()=>[],searchEvidence:()=>[],getGlossary:()=>[]};
vm.runInNewContext(fs.readFileSync(path.join(root,'server.js'),'utf8'),{require:n=>n==='http'?{createServer:f=>(handler=f,{listen(){}})}:n==='fs'?fs:n==='path'?path:n.includes('firebaseAuth')?auth:n.includes('storageService')?storage:n.includes('knowledgeService')?knowledge:forbidden,__dirname:root,process:{env:{},loadEnvFile(){}},console:{log(){},warn(){}},URLSearchParams,Buffer,setTimeout,clearTimeout,setInterval,clearInterval});
function request(url,method='GET',cookie='',body){return new Promise((resolve,reject)=>{const req=Readable.from(body?[JSON.stringify(body)]:[]);req.url=url;req.method=method;req.headers={cookie,origin:'http://127.0.0.1:3000'};const chunks=[];const res=new Writable({write(c,e,cb){chunks.push(c);cb();}});res.headers={};res.setHeader=(k,v)=>res.headers[k]=v;res.writeHead=(s,h)=>{res.status=s;Object.assign(res.headers,h||{})};res.on('finish',()=>resolve({status:res.status,json:()=>JSON.parse(Buffer.concat(chunks))}));Promise.resolve(handler(req,res)).catch(reject);});}
test('protected APIs require a verified session',async()=>assert.equal((await request('/api/auth/me')).status,401));
test('students cannot call teacher APIs',async()=>assert.equal((await request('/api/teacher/class-settings','GET','student')).status,403));
test('teacher class scope comes from verified profile, not query',async()=>{const r=await request('/api/teacher/class-settings?schoolId=other&grade=9&classId=9','GET','teacher');assert.equal(r.status,200);assert.deepEqual(captured,['school-a',1,2]);});
test('students can only request their own detailed growth record',async()=>assert.equal((await request('/api/growth/student/other','GET','student')).status,403));
test('student room response omits teacher observations',async()=>{const r=await request('/api/debate/room/r','GET','student');assert.equal(r.status,200);assert.equal(r.json().teacherObservations,undefined);});
test('teacher-only room initialization is enforced',async()=>assert.equal((await request('/api/debate/room/init','POST','student',{})).status,403));

