'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {LearningService,promptContext}=require('./services/learningService'),plans=require('./services/lessonPlan'),questions=require('./services/writingQuestions');
const teacher={uid:'t',role:'teacher',schoolId:'one'},student={uid:'s',role:'student',schoolId:'one'};
function fixture(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'lesson-authoring-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));return new LearningService(path.join(dir,'teaching.json'));}
test('all 43 topics include distinct protagonists, contextual concepts, references and independent judgment',t=>{const service=fixture(t);for(const topic of service.list(student)){const p=service.teacherMaterial(topic.topicId,teacher).plan;plans.validate(p);assert.doesNotMatch(p.proposition,/는가$|한가$|인가$/);assert.ok(p.characters.length>=2);assert.notEqual(p.characters[0].context,p.characters[1].context);assert.notEqual(p.characters[0].position,p.characters[1].position);const lesson=service.lesson(topic.topicId,student);for(const c of p.characters)assert.ok(lesson.scenario.story.includes(c.name));assert.match(lesson.scenario.choiceQuestion,/입장에서 제시한/);assert.match(lesson.scenario.choiceQuestion,/자신의 판단/);assert.doesNotMatch(JSON.stringify(lesson.scenario),/해요|있어요|없어요|할까요|동의하나요/);assert.ok(p.conceptApplications.length&&p.textbookRef&&p.debateGoal&&p.essayGoal);for(const o of lesson.scenario.options)assert.doesNotMatch(o.claim,/입장에서/);}});
test('teacher edits survive restart, stay school-scoped, preserve keyword changes and reach every coach',t=>{const s=fixture(t),id='curriculum_1_02',p=s.teacherMaterial(id,teacher).plan;p.characters[1].context='이월세 청년은 3주 뒤 집을 비워야 합니다. 올해 임대료 지원을 요청합니다.';p.question='공공 임대와 긴급 지원 중 무엇을 우선할 것인가?';p.textbookRef='교사 확인: 미래엔 17쪽';p.debateGoal='두 달과 3주라는 시간 차이를 비교합니다.';p.conceptApplications[0].application='세 주 안에 머물 집이 필요한 처지와 연결합니다.';
 const saved=s.savePlan(id,teacher,{revision:0,plan:p});assert.equal(saved.revision,1);const restarted=new LearningService(s.file);assert.equal(restarted.lesson(id,student).topic.question,p.question);assert.notEqual(s.lesson(id,{...student,schoolId:'other'}).topic.question,p.question);assert.throws(()=>s.savePlan(id,student,{revision:1,plan:p}),e=>e.status===403);assert.throws(()=>s.savePlan(id,teacher,{revision:0,plan:p}),e=>e.status===409);
 const word=s.keywords(teacher).keywords[0];s.mutate(teacher,'PUT',word.id,{...word,revision:1,definition:'교사 수정 정의'});assert.equal(s.lesson(id,student).topic.question,p.question);for(const mode of ['basic','advanced','speech']){const c=s.coaching(id,student,mode);assert.match(promptContext(c),/3주 뒤/);assert.match(promptContext(c),/두 달과 3주/);}assert.match(JSON.stringify(questions.contextOf(s.lesson(id,student))),/세 주 안에/);
 const bad=structuredClone(p);bad.characters.pop();assert.throws(()=>s.savePlan(id,teacher,{revision:2,plan:bad}),e=>e.status===400);bad.characters=p.characters;bad.claimant='없는 인물';assert.throws(()=>s.savePlan(id,teacher,{revision:2,plan:bad}),e=>e.status===400);});
test('drafts persist and isolate students, schools, topics and activity modes; stale saves cannot replace content',t=>{const s=fixture(t),id='curriculum_1_02',basic={claim:'동의합니다.',reason:'3주 안에 지원이 필요합니다.',rebuttal:'장기 공급도 필요합니다.',stance:'pro'};s.drafts.save(student,id,{mode:'basic',revision:0,content:basic});s.drafts.save(student,id,{mode:'advanced',revision:0,content:{paragraphs:['서론','본론','결론'],writingPlan:{targetChars:600,targetSentences:12,targetParagraphs:3}}});assert.deepEqual(new LearningService(s.file).drafts.get(student,id).basic.content,basic);for(const other of [{...student,uid:'someone'},{...student,schoolId:'other'}])assert.deepEqual(s.drafts.get(other,id),{});assert.deepEqual(s.drafts.get(student,'curriculum_1_01'),{});assert.throws(()=>s.drafts.save(student,id,{mode:'basic',revision:0,content:{...basic,reason:'덮어쓰기'}}),e=>e.status===409);assert.equal(s.drafts.get(student,id).basic.content.reason,basic.reason);});
test('HTTP permissions and no-store apply to lesson editing and own draft retrieval',async t=>{const s=fixture(t),h=require('./tests/helpers/learning-server.cjs').build(s.file),server=await h.start();t.after(server.close);const call=(url,role,method='GET',body,origin=server.origin)=>fetch(server.origin+url,{method,headers:{cookie:role?'test_role='+role:'',origin,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const url='/api/teacher/materials/curriculum_1_02';assert.equal((await call(url,'student','PUT',{})).status,403);const got=await (await call(url,'teacher')).json();assert.equal((await call(url,'teacher','PUT',{revision:got.revision,plan:got.plan})).status,200);assert.equal((await call(url,'teacher','PUT',{revision:1,plan:got.plan},'https://outside.invalid')).status,403);const draft='/api/learning/drafts/curriculum_1_02';assert.equal((await call(draft,'')).status,401);let r=await call(draft,'student','PUT',{userId:'other',mode:'basic',revision:0,content:{claim:'나의 글',reason:'나의 이유',rebuttal:'',stance:'pro'}});assert.equal(r.status,200);r=await call(draft,'student');assert.equal(r.headers.get('cache-control'),'no-store');assert.equal((await r.json()).drafts.basic.content.claim,'나의 글');assert.deepEqual((await (await call(draft,'teacher')).json()).drafts,{});assert.equal((await call('/api/learning/drafts/not-a-topic','student')).status,404);assert.equal((await fetch(server.origin+'/data/teaching-config.json.drafts.json')).status,404);});
test('speech outline preserves supplied content and supports one or several paragraphs',()=>{const outline=require('./assets/speech-outline');assert.deepEqual(outline.fromText('판단입니다.\n\n이유입니다.\n\n조건입니다.'),{claim:'판단입니다.',reason:'이유입니다.',condition:'조건입니다.'});assert.deepEqual(outline.fromText('동의합니다. 주거가 필요합니다. 대안이 있습니다. 조건이 필요합니다.'),{claim:'동의합니다.',reason:'주거가 필요합니다. 대안이 있습니다.',condition:'조건이 필요합니다.'});assert.deepEqual(outline.bullets('<script>원문</script>'),['<script>원문</script>']);});

test('previous writing is returned oldest to newest so import selects the latest own topic draft',async t=>{const s=fixture(t),h=require('./tests/helpers/learning-server.cjs').build(s.file),server=await h.start();t.after(server.close);for(let i=1;i<=35;i++)h.sessions.push({userId:h.users.student.uid,topicId:'curriculum_1_02',mode:'basic_practice',claim:'claim '+i,reason:'reason '+i,createdAt:new Date(2026,0,i).toISOString()});h.sessions.push({userId:'someone-else',topicId:'curriculum_1_02',mode:'basic_practice',claim:'private',createdAt:new Date(2026,5,1).toISOString()});const r=await fetch(server.origin+'/api/learning/drafts/curriculum_1_02',{headers:{cookie:'test_role=student'}}),d=await r.json();assert.equal(d.previous.length,30);assert.equal(d.previous.at(-1).content.claim,'claim 35');assert.equal(d.previous[0].content.claim,'claim 6');assert.ok(!JSON.stringify(d).includes('private'));});
